### ISSUE TITLE
Cant compile with g++ version 11.1.0

### ISSUE THREAD

**Issue by qdlmcfresh** [HoShiMin/Sig#1]
Hi, i tried your example code and sadly cant compile it on linux with g++ 11.1.0 which is the newest for my distro.

I tried the following code:
```
#include "Sig.hpp"

#include <cassert>

static const unsigned char g_arr[]{
    '?', '?', '?', '?',
    0x11, 0x22, 0x33, 0x44};

int main()
{
    const void *const found1 = Sig::find<Sig::Dword<0x44332211>>(g_arr, sizeof(g_arr));

    const void *const found2 = Sig::find<
        Sig::Mask::Eq<'.'>,
        Sig::Mask::Any<'?'>>(g_arr, sizeof(g_arr), "\x11\x22\x00\x44", "..?.");

    const void *const found3 = Sig::find(g_arr, sizeof(g_arr), "11 22 ? 44");

    assert(found1 == &g_arr[4]);
    assert(found1 == found2);
    assert(found2 == found3);

    return 0;
}
```
and got these errors:
```
In file included from test.cpp:1:
Sig.hpp:297:15: error: explicit specialization in non-namespace scope ‘struct Sig’
  297 |     template <>
      |               ^
Sig.hpp:298:12: error: too few template-parameter-lists
  298 |     struct SetComparator<>
      |            ^~~~~~~~~~~~~~~
Sig.hpp:444:15: error: explicit specialization in non-namespace scope ‘struct Sig’
  444 |     template <>
      |               ^
Sig.hpp:445:12: error: too few template-parameter-lists
  445 |     struct Comparator<>
      |            ^~~~~~~~~~~~
Sig.hpp:822:15: error: explicit specialization in non-namespace scope ‘struct Sig’
  822 |     template <>
      |               ^
Sig.hpp:823:12: error: too few template-parameter-lists
  823 |     struct MaskComparator<>
      |            ^~~~~~~~~~~~~~~~
Sig.hpp: In instantiation of ‘static bool Sig::Comparator<Entry>::cmp(const void*) [with Entry = Sig::Holder<unsigned int, Sig::Cmp::Eq, 1144201745>]’:
Sig.hpp:464:60:   required from ‘static const void* Sig::find(const void*, size_t) [with Entries = {Sig::Holder<unsigned int, Sig::Cmp::Eq, 1144201745>}; size_t = long unsigned int]’
test.cpp:11:65:   required from here
Sig.hpp:403:45: error: no type named ‘cmp’ in ‘using Cmp = struct Sig::Cmp::Eq<unsigned int, 1144201745>’ {aka ‘struct Sig::Cmp::Eq<unsigned int, 1144201745>’}
  403 |                 return typename Entry::Cmp::cmp(pos);
      |                                             ^~~~~~~~
Sig.hpp: In instantiation of ‘static bool Sig::MaskComparator<Entry, Entries ...>::cmp(char, char, char) [with Entry = Sig::Mask::Any<'?'>; Entries = {}]’:
Sig.hpp:794:55:   required from ‘static bool Sig::MaskComparator<Entry, Entries ...>::cmp(char, char, char) [with Entry = Sig::Mask::Eq<'.'>; Entries = {Sig::Mask::Any<'?'>}]’
Sig.hpp:854:73:   required from ‘static const void* Sig::find(const void*, size_t, const char*, const char*, size_t) [with Comparators = {Sig::Mask::Eq<'.'>, Sig::Mask::Any<'?'>}; size_t = long unsigned int]’
Sig.hpp:882:36:   required from ‘static const void* Sig::find(const void*, size_t, const char*, const char*) [with Comparators = {Sig::Mask::Eq<'.'>, Sig::Mask::Any<'?'>}; size_t = long unsigned int]’
test.cpp:15:29:   required from here
Sig.hpp:794:55: error: ‘cmp’ is not a member of ‘Sig::MaskComparator<>’
  794 |                 return MaskComparator<Entries...>::cmp(data, pattern, mask);
```

**Comment by HoShiMin** [comment]
Hm, looks like msvc and gcc work with templates in different ways... Well, I'll check it.

**Comment by HoShiMin** [comment]
Fixed

**Comment by qdlmcfresh** [comment]
Thx :)
